const devices = [
  {
    id: 'agv-001',
    type: 'agv',
    position: { x: 10, y: 0, z: 5 },
    status: 'normal',
    temperature: 42,
    battery: 88,
  },
  {
    id: 'agv-002',
    type: 'agv',
    position: { x: 25, y: 0, z: 12 },
    status: 'normal',
    temperature: 38,
    battery: 72,
  },
  {
    id: 'agv-003',
    type: 'agv',
    position: { x: 40, y: 0, z: 8 },
    status: 'normal',
    temperature: 55,
    battery: 65,
  },
  {
    id: 'agv-004',
    type: 'agv',
    position: { x: 15, y: 0, z: 30 },
    status: 'normal',
    temperature: 48,
    battery: 91,
  },
  {
    id: 'agv-005',
    type: 'agv',
    position: { x: 55, y: 0, z: 20 },
    status: 'normal',
    temperature: 61,
    battery: 54,
  },
  {
    id: 'sensor-001',
    type: 'sensor',
    position: { x: 5, y: 2, z: 0 },
    status: 'normal',
    temperature: 35,
    battery: 100,
  },
  {
    id: 'sensor-002',
    type: 'sensor',
    position: { x: 20, y: 2, z: 15 },
    status: 'normal',
    temperature: 72,
    battery: 95,
  },
  {
    id: 'sensor-003',
    type: 'sensor',
    position: { x: 35, y: 2, z: 10 },
    status: 'normal',
    temperature: 68,
    battery: 90,
  },
  {
    id: 'sensor-004',
    type: 'sensor',
    position: { x: 50, y: 2, z: 25 },
    status: 'normal',
    temperature: 58,
    battery: 85,
  },
  {
    id: 'sensor-005',
    type: 'sensor',
    position: { x: 60, y: 2, z: 5 },
    status: 'normal',
    temperature: 44,
    battery: 92,
  },
];

module.exports = { devices };
